# Generated by Django 3.1.1 on 2020-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'waitBuyer'), (2, 'waitSend'), (3, 'sent')], default=1),
        ),
    ]
