# Generated by Django 3.1.1 on 2020-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_auto_20200930_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='productDetail',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='sendAddress',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
