# Generated by Django 3.1.1 on 2020-09-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_auto_20200930_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyerName',
            field=models.CharField(default='รอผู้ซื้อกรอกข้อมูล', max_length=50),
        ),
    ]
