# Generated by Django 3.1.1 on 2020-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_auto_20200930_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyerName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
